language: node_js
node_js:
- '0.10'
before_install:
- curl https://install.meteor.com | /bin/sh
after_success:
- make build
env:
  global:
    - ARTIFACTS_S3_REGION=eu-west-1
    - ARTIFACTS_TARGET_PATHS="$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER:$TRAVIS_REPO_SLUG/$TRAVIS_COMMIT"
addons:
  artifacts:
    key:
      secure: GV/Ysn8/xmMbAje4P/1+zi0YaclhcocoRnaKxYEFSMgyQ50cVxILlESyeuzQZ57e7V9BJF4Ka9Gwghnchv/V3lknq4KilH8+dvQoRDWaLSUcAsBPjIo1W6G0ATHdq8o76f/jxhJavcqhpBkUaZY0u/EFl+auk8imRYGyIOg1pPs=
    secret:
      secure: B5e5K82shrQS/DZDm7U7zYpEzqGFZViO4o+WUsAY6HKEcQt2KAoql2HnlvDiIfco2sU6QkAHvdUvXRQ8Xn6kqCU8w4uJp+iVtnd5mzRQWU7dTyuZyqBxPtvBic6lSbOq4ArqCIu4sBjbxAUGxMrdkCwJqDGv/nePcZGuNTpVnXg=
    bucket: foftravel-builds
    paths:
      - build/meteor_testing.tar.gz
