language: node_js
node_js:
- '0.10'
before_install:
- curl https://install.meteor.com | /bin/sh
before_script:
- gem install travis-artifacts
after_success:
- make build
- travis-artifacts upload --path build/helloworld.tgz --target-path builds
env:
  global:
  - ARTIFACTS_AWS_REGION=eu-west-1
  - ARTIFACTS_S3_BUCKET=foftravel_builds
  - secure: NJ4qeJXe5bKgRs+FrhoPf7bmiu/y3dSarX0HDyaI14dYnzrP7dMJ+5b2VmfjPPuvJ/dzvKC+oTmkyinjyxVujlRzjeXOkcBUmo9YB22hdJeIemQ5GbZIEmpRew0C6UFPJZ5gF2FX7YMZk6tVhBKRLhNcuh1ueuTRY26jo0KWJAc=
  - secure: kQUlCf4/fGi1o4+si2vqpXZVvijFpQZ0Y360iRxGpgXYZCyc7cWlex21tmbFkNJOU6bxb+uaNrQUKutuMt6LD+8vX16esoyNAhf/wCY02vHIdluyNUjZ0BamuH8I0fvazTmVf9hcsHQpV/3V4/rXcsSPArMa/iLXxfEkop6Mokg=
